# copied from https://github.com/bioconda/bioconda-recipes/blob/9c08a16bac9b7d0a076578823d5008b8bbfc466e/recipes/toil/meta.yaml
{% set name = "toil" %}
{% set version = "9.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a53f2d4f6008cf44ef432571d3073aa23b7eb6c3795db3c168f7882f4622cfa9

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --no-cache-dir -vvv
  entry_points:
    - toil = toil.utils.toilMain:main
    - _toil_worker = toil.worker:main
    - toil-cwl-runner = toil.cwl.cwltoil:main
    - toil-wdl-runner = toil.wdl.wdltoil:main
    - toil-wes-cwl-runner = toil.server.cli.wes_cwl_runner:main
    - _toil_mesos_executor = toil.batchSystems.mesos.executor:main
    - _toil_contained_executor = toil.batchSystems.contained_executor:executor

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools >=65.5.1,<83
    - wheel
  run:
    - python >={{ python_min }}
    - dill >=0.3.2,<0.4
    - requests >2,<=2.32.5
    - docker-py >=6.1.0,<8
    - urllib3 >=1.26.0,<3
    - python-dateutil
    - psutil >=6.1.0,<8
    - pypubsub >=4.0.3,<5
    - addict >=2.2.1,<2.5
    - enlighten >=1.5.2,<2
    - configargparse >=1.7,<2
    - ruamel.yaml >=0.15
    - pyyaml >=6,<7
    - typing-extensions >=4.6.2,<5
    - coloredlogs >=15,<16
    - prompt_toolkit >=3.0,<4
    #mesos pymesos isn't available
    #server reqs
    # - wes-service is missing
    # so commenting out the remaining server reqs for now
    # - connexion >=2.10.0, <4
    # - flask >=2.0,<4
    # - werkzeug >=2.0,<4
    # - flask-cors ==5.0.0
    # - gunicorn ==23.0.0
    # - celery >=5.1.0, <6
    #aws reqs
    # mypy-boto3-iam & ec2_metadata are not yet in Conda
    - boto3-stubs >=1.28.3.post2,<2
    # - mypy-boto3-iam >=1.28.3.post2,<2
    - mypy-boto3-s3 >=1.28.3.post3,<2
    - moto >=5.0.3,<6
    # - ec2_metadata <3
    #encryption reqs
    - pynacl >=1.4.0,<2
    #google reqs
    - apache-libcloud >=3.6.1,<4
    - google-cloud-storage >=2,<=2.8.0
    - google-auth >=2.18.1,<3
    #cwl reqs
    - cwltool ==3.1.20260108082145
    - schema-salad >=8.4.20230128170514,<9
    - galaxy-tool-util <26
    - ruamel.yaml >=0.15,<=0.19.1
    - ruamel.yaml.clib >=0.2.6
    - networkx <4
    - cachecontrol-with-filecache
    - cwl-utils >=0.36
    #htcondor reqs
    - python-htcondor >=23.6.0,<25
    #kubernetes reqs
    - python-kubernetes >=12.0.1,<36
    - idna >=2
    #wdl reqs
    - miniwdl ==1.13.1

test:
  imports:
    - toil
    - toil.batchSystems
    - toil.cwl
    - toil.fileStores
    - toil.jobStores
    - toil.jobStores.aws
    - toil.lib
    - toil.lib.encryption
    - toil.provisioners
    - toil.provisioners.aws
    - toil.server
    - toil.server.api_spec
    - toil.server.cli
    - toil.server.wes
    - toil.test
    - toil.utils
    - toil.wdl
  commands:
    - toil --help
    - _toil_worker --help
    - toil-cwl-runner --help
    - pip check
  requires:
    - pip
    - python {{ python_min }}
    - pytest
    - rsync

about:
  home: 'https://toil.ucsc-cgl.org/'
  summary: 'A scalable, efficient, cross-platform and easy-to-use workflow engine in pure Python'
  dev_url: 'https://github.com/DataBiosphere/toil'
  doc_url: 'https://toil.readthedocs.io/en/latest/'
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE

extra:
  recipe-maintainers:
    - sameeul
    - mr-c
